
    import turtle
    import time
    from random import randint
    number = (randint(1,3))
    print("You have chosen hangman")
    time.sleep(1)
    print("The rules are standard")
    time.sleep(1)
    print("Lets Begin")
    time.sleep(1)
    print("The game will appear on the screen that will open soon")
    time.sleep(1)
    print("There is a program that will draw hangman on the new screen")
    time.sleep(1)
    print("Once you found the whole word, type 'done'.") 
    wn = turtle. Screen()
    alex = turtle. Turtle()
    alex.pendown()
    alex.forward(30)
    alex.back(60)
    alex.forward(30)
    alex.left(90)
    alex.forward(250)
    alex.right(90)
    alex.forward(175)
    alex.right(90)
    alex.forward(75)
    alex.penup()
    alex.forward(300)
    alex.left(90)
    alex.forward(100)
    alex.right(180)
    alex.pendown()
    alex.forward(50)
    alex.penup()
    alex.forward(50)
    alex.pendown()
    alex.forward(50)
    alex.penup()
    alex.forward(50)
    alex.pendown()
    alex.forward(50)
    alex.penup()
    alex.forward(50)
    alex.pendown()
    alex.forward(50)
    alex.penup()
    alex.forward(50)
    alex.pendown()
    alex.forward(50)
    alex.penup()
    if number == 1:
        word = "APPLE"
    if number == 2:
        word = "CRAZY"
    if number == 3:
        word = "TAXES"
    errors = 0
    a = 7
    b = 7
    while a == b:
        guess = input("Guess a letter that is capitalized, type it, and press enter.")
        if word == "APPLE":
            if guess == "A":
                alex.penup()
                alex.setpos(-170.00,-120.00)
                alex.right(120)
                alex.pendown()
                alex.forward(30)
                alex.right(120)
                alex.forward(30)
                alex.back(15)
                alex.right(120)
                alex.forward(16)
                alex.penup()
            elif guess == "P":
                alex.penup()
                alex.setpos(-50.00, -120.00)
                alex.pendown()
                alex.right(90)
                alex.forward(40)
                alex.right(90)
                alex.forward(20)
                alex.right(90)
                alex.forward(20)
                alex.right(90)
                alex.forward(20)
                alex.penup()
                alex.setpos(40.00, -120.00)
                alex.pendown()
                alex.right(90)
                alex.forward(40)
                alex.right(90)
                alex.forward(20)
                alex.right(90)
                alex.forward(20)
                alex.right(90)
                alex.forward(20)
                alex.penup()
            elif guess == "L":
                alex.penup()
                alex.setpos(130.00, -120.00)
                alex.pendown()
                alex.right(90)
                alex.forward(40)
                alex.back(40)
                alex.right(90)
                alex.forward(25)
                alex.right(180)
                alex.forward(25)
                alex.penup()
            elif guess == "E":
                alex.penup()
                alex.setpos(250.00, -120.00)
                alex.pendown()
                alex.right(90)
                alex.forward(40)
                alex.right(90)
                alex.forward(20)
                alex.back(20)
                alex.right(90)
                alex.forward(20)
                alex.left(90)
                alex.forward(20)
                alex.back(20)
                alex.right(90)
                alex.forward(20)
                alex.left(90)
                alex.forward(20)
                alex.right(180)
                alex.forward(20)
            elif guess == "done":
                print("You win!!!")
                cont = input("Continue playing? Yes or No?")
                if cont == "Yes":
                    turtle.resetscreen()
                    alex.pendown()
                    alex.forward(30)
                    alex.back(60)
                    alex.forward(30)
                    alex.left(90)
                    alex.forward(250)
                    alex.right(90)
                    alex.forward(175)
                    alex.right(90)
                    alex.forward(75)
                    alex.penup()
                    alex.forward(300)
                    alex.left(90)
                    alex.forward(100)
                    alex.right(180)
                    alex.pendown()
                    alex.forward(50)
                    alex.penup()
                    alex.forward(50)
                    alex.pendown()
                    alex.forward(50)
                    alex.penup()
                    alex.forward(50)
                    alex.pendown()
                    alex.forward(50)
                    alex.penup()
                    alex.forward(50)
                    alex.pendown()
                    alex.forward(50)
                    alex.penup()
                    alex.forward(50)
                    alex.pendown()
                    alex.forward(50)
                    alex.penup()
                    continue
                elif cont == "No":
                    turtle.bye()
                    return
            else:
                errors = errors + 1
                if errors == 1:
                    alex.penup()
                    alex.setpos(175.00, 175.00)
                    alex.pendown()
                    alex.circle(20)
                elif errors == 2:
                    alex.penup()
                    alex.setpos(175.00, 135.00)
                    alex.left(90)
                    alex.pendown()
                    alex.forward(50)
                    alex.right(90)
                elif errors == 3:
                    alex.penup()
                    alex.setpos(175.00, 115.00)
                    alex.right(45)
                    alex.pendown()
                    alex.forward(30)
                    alex.left(45)
                elif errors == 4:
                    alex.penup()
                    alex.setpos(175.00, 115.00)
                    alex.pendown()
                    alex.right(135)
                    alex.forward(30)
                    alex.right(225)
                elif errors == 5:
                    alex.penup()
                    alex.setpos(175.00, 85.00)
                    alex.left(45)
                    alex.pendown()
                    alex.forward(30)
                    alex.right(45)
                elif errors == 6:
                    alex.penup()
                    alex.setpos(175.00, 85.00)
                    alex.left(135)
                    alex.pendown()
                    alex.forward(30)
                    alex.right(135)
                elif errors == 7:
                    print("Game Over!!!")
                    cont = input("Continue playing? Yes or No?")
                    if cont == "Yes":
                        turtle.resetscreen()
                        alex.pendown()
                        alex.forward(30)
                        alex.back(60)
                        alex.forward(30)
                        alex.left(90)
                        alex.forward(250)
                        alex.right(90)
                        alex.forward(175)
                        alex.right(90)
                        alex.forward(75)
                        alex.penup()
                        alex.forward(300)
                        alex.left(90)
                        alex.forward(100)
                        alex.right(180)
                        alex.pendown()
                        alex.forward(50)
                        alex.penup()
                        alex.forward(50)
                        alex.pendown()
                        alex.forward(50)
                        alex.penup()
                        alex.forward(50)
                        alex.pendown()
                        alex.forward(50)
                        alex.penup()
                        alex.forward(50)
                        alex.pendown()
                        alex.forward(50)
                        alex.penup()
                        alex.forward(50)
                        alex.pendown()
                        alex.forward(50)
                        alex.penup()
                        continue
                    elif cont == "No":
                        turtle.bye()
                        return
        if word == "CRAZY":
            if guess == "C":
               alex.penup()
               alex.setpos(-150.00, -90.00)
               alex.pendown()
               alex.circle(20, 180)
               alex.right(180)
            elif guess == "R":
                alex.penup()
                alex.setpos(-50.00, -120.00)
                alex.right(90)
                alex.pendown()
                alex.forward(40)
                alex.right(90)
                alex.forward(15)
                alex.right(90)
                alex.forward(15)
                alex.right(90)
                alex.forward(15)
                alex.left(135)
                alex.forward(30)
                alex.right(135)
            elif guess == "A":
                alex.penup()
                alex.setpos(40.00,-125.00)
                alex.right(120)
                alex.pendown()
                alex.forward(30)
                alex.right(120)
                alex.forward(30)
                alex.back(15)
                alex.right(120)
                alex.forward(16)
                alex.penup()
            elif guess == "Z":
                alex.penup()
                alex.setpos(130.00, -120.00)
                alex.pendown()
                alex.back(40)
                alex.forward(40)
                alex.right(135)
                alex.forward(40)
                alex.left(135)
                alex.forward(40)
            elif guess == "Y":
                alex.penup()
                alex.setpos(270.00, -120.00)
                alex.right(90)
                alex.pendown()
                alex.forward(25)
                alex.left(45)
                alex.forward(15)
                alex.back(15)
                alex.right(90)
                alex.forward(15)
                alex.left(135)
            elif guess == "done":
                print("You win!!!")
                cont = input("Continue playing? Yes or No?")
                if cont == "Yes":
                    turtle.resetscreen()
                    alex.pendown()
                    alex.forward(30)
                    alex.back(60)
                    alex.forward(30)
                    alex.left(90)
                    alex.forward(250)
                    alex.right(90)
                    alex.forward(175)
                    alex.right(90)
                    alex.forward(75)
                    alex.penup()
                    alex.forward(300)
                    alex.left(90)
                    alex.forward(100)
                    alex.right(180)
                    alex.pendown()
                    alex.forward(50)
                    alex.penup()
                    alex.forward(50)
                    alex.pendown()
                    alex.forward(50)
                    alex.penup()
                    alex.forward(50)
                    alex.pendown()
                    alex.forward(50)
                    alex.penup()
                    alex.forward(50)
                    alex.pendown()
                    alex.forward(50)
                    alex.penup()
                    alex.forward(50)
                    alex.pendown()
                    alex.forward(50)
                    alex.penup()
                    continue
                elif cont == "No":
                    turtle.bye()
                    return
            else:
                errors = errors + 1
                if errors == 1:
                    alex.penup()
                    alex.setpos(175.00, 175.00)
                    alex.pendown()
                    alex.circle(20)
                elif errors == 2:
                    alex.penup()
                    alex.setpos(175.00, 135.00)
                    alex.left(90)
                    alex.pendown()
                    alex.forward(50)
                    alex.right(90)
                elif errors == 3:
                    alex.penup()
                    alex.setpos(175.00, 115.00)
                    alex.right(45)
                    alex.pendown()
                    alex.forward(30)
                    alex.left(45)
                elif errors == 4:
                    alex.penup()
                    alex.setpos(175.00, 115.00)
                    alex.pendown()
                    alex.right(135)
                    alex.forward(30)
                    alex.right(225)
                elif errors == 5:
                    alex.penup()
                    alex.setpos(175.00, 85.00)
                    alex.left(45)
                    alex.pendown()
                    alex.forward(30)
                    alex.right(45)
                elif errors == 6:
                    alex.penup()
                    alex.setpos(175.00, 85.00)
                    alex.left(135)
                    alex.pendown()
                    alex.forward(30)
                    alex.right(135)
                elif errors == 7:
                    print("Game Over!!!")
                    cont = input("Continue playing? Yes or No?")
                    if cont == "Yes":
                        turtle.resetscreen()
                        alex.pendown()
                        alex.forward(30)
                        alex.back(60)
                        alex.forward(30)
                        alex.left(90)
                        alex.forward(250)
                        alex.right(90)
                        alex.forward(175)
                        alex.right(90)
                        alex.forward(75)
                        alex.penup()
                        alex.forward(300)
                        alex.left(90)
                        alex.forward(100)
                        alex.right(180)
                        alex.pendown()
                        alex.forward(50)
                        alex.penup()
                        alex.forward(50)
                        alex.pendown()
                        alex.forward(50)
                        alex.penup()
                        alex.forward(50)
                        alex.pendown()
                        alex.forward(50)
                        alex.penup()
                        alex.forward(50)
                        alex.pendown()
                        alex.forward(50)
                        alex.penup()
                        alex.forward(50)
                        alex.pendown()
                        alex.forward(50)
                        alex.penup()
                        continue
                    elif cont == "No":
                        turtle.bye()
                        return
        if word == "TAXES":
            if guess == "T":
                alex.penup()
                alex.setpos(-150.00,-120.00)
                alex.right(90)
                alex.pendown()
                alex.forward(40)
                alex.left(90)
                alex.forward(20)
                alex.back(40)
            elif guess == "A":
                alex.penup()
                alex.setpos(-65.00, -120.00)
                alex.right(120)
                alex.pendown()
                alex.forward(30)
                alex.right(120)
                alex.forward(30)
                alex.back(15)
                alex.right(120)
                alex.forward(16)
                alex.penup()
            elif guess == "X":
                alex.penup()
                alex.setpos(30.00,-125.00)
                alex.right(135)
                alex.pendown()
                alex.forward(50)
                alex.back(25)
                alex.right(90)
                alex.forward(25)
                alex.back(50)
                alex.right(135)
            elif guess == "E":
                alex.penup()
                alex.setpos(130.00, -120.00)
                alex.pendown()
                alex.right(90)
                alex.forward(40)
                alex.right(90)
                alex.forward(20)
                alex.back(20)
                alex.right(90)
                alex.forward(20)
                alex.left(90)
                alex.forward(20)
                alex.back(20)
                alex.right(90)
                alex.forward(20)
                alex.left(90)
                alex.forward(20)
                alex.right(180)
                alex.forward(20)
            elif guess == "S":
                alex.penup()
                alex.setpos(230.00, -120.00)
                alex.right(180)
                alex.pendown()
                alex.forward(40)
                alex.left(90)
                alex.forward(20)
                alex.left(90)
                alex.forward(40)
                alex.right(90)
                alex.forward(20)
                alex.right(90)
                alex.forward(40)
                alex.right(180)
            elif guess == "done":
                print("You win!!!")
                cont = input("Continue playing? Yes or No?")
                if cont == "Yes":
                    turtle.resetscreen()
                    alex.pendown()
                    alex.forward(30)
                    alex.back(60)
                    alex.forward(30)
                    alex.left(90)
                    alex.forward(250)
                    alex.right(90)
                    alex.forward(175)
                    alex.right(90)
                    alex.forward(75)
                    alex.penup()
                    alex.forward(300)
                    alex.left(90)
                    alex.forward(100)
                    alex.right(180)
                    alex.pendown()
                    alex.forward(50)
                    alex.penup()
                    alex.forward(50)
                    alex.pendown()
                    alex.forward(50)
                    alex.penup()
                    alex.forward(50)
                    alex.pendown()
                    alex.forward(50)
                    alex.penup()
                    alex.forward(50)
                    alex.pendown()
                    alex.forward(50)
                    alex.penup()
                    alex.forward(50)
                    alex.pendown()
                    alex.forward(50)
                    alex.penup()
                    continue
                elif cont == "No":
                    turtle.bye()
                    return 
            else:
                errors = errors + 1
                if errors == 1:
                    alex.penup()
                    alex.setpos(175.00, 175.00)
                    alex.pendown()
                    alex.circle(20)
                elif errors == 2:
                    alex.penup()
                    alex.setpos(175.00, 135.00)
                    alex.left(90)
                    alex.pendown()
                    alex.forward(50)
                    alex.right(90)
                elif errors == 3:
                    alex.penup()
                    alex.setpos(175.00, 115.00)
                    alex.right(45)
                    alex.pendown()
                    alex.forward(30)
                    alex.left(45)
                elif errors == 4:
                    alex.penup()
                    alex.setpos(175.00, 115.00)
                    alex.pendown()
                    alex.right(135)
                    alex.forward(30)
                    alex.right(225)
                elif errors == 5:
                    alex.penup()
                    alex.setpos(175.00, 85.00)
                    alex.left(45)
                    alex.pendown()
                    alex.forward(30)
                    alex.right(45)
                elif errors == 6:
                    alex.penup()
                    alex.setpos(175.00, 85.00)
                    alex.forward(135)
                    alex.pendown()
                    alex.forward(30)
                    alex.right(135)
                elif errors == 7:
                    print("Game Over!!!")
                    cont = input("Continue playing? Yes or No?")
                    if cont == "Yes":
                        turtle.resetscreen()
                        alex.pendown()
                        alex.forward(30)
                        alex.back(60)
                        alex.forward(30)
                        alex.left(90)
                        alex.forward(250)
                        alex.right(90)
                        alex.forward(175)
                        alex.right(90)
                        alex.forward(75)
                        alex.penup()
                        alex.forward(300)
                        alex.left(90)
                        alex.forward(100)
                        alex.right(180)
                        alex.pendown()
                        alex.forward(50)
                        alex.penup()
                        alex.forward(50)
                        alex.pendown()
                        alex.forward(50)
                        alex.penup()
                        alex.forward(50)
                        alex.pendown()
                        alex.forward(50)
                        alex.penup()
                        alex.forward(50)
                        alex.pendown()
                        alex.forward(50)
                        alex.penup()
                        alex.forward(50)
                        alex.pendown()
                        alex.forward(50)
                        alex.penup()
                        continue
                    elif cont == "No":
                        turtle.bye()
                        return
