print("Hi, Welcome to ... Mad Libs")
    print("Fill in the required information and see the result!!!")
    plural_noun1 = input("Insert a plural noun")
    plural_noun2 = input("Insert a plural noun")
    plural_noun3 = input("Insert a plural noun")
    number1 = input("Insert a number.")
    plural_noun4 = input("Insert a plural noun")
    noun1 = input("Insert a noun")
    noun2 = input("Insert a noun")
    noun3 = input("Insert a noun")
    noun4 = input("Insert a noun.")
    part_of_body1 = input("Insert a part of the body.")
    letter_of_the_alphabet1 = input("Insert a letter of the alphabet.")
    plural_noun5 = input("Insert a plural noun")
    plural_noun6 = input("Insert a plural noun")
    plural_noun7 = input("Insert a plural noun")
    part_of_body2 = input("Insert a part of the body.")
    part_of_body3 = input("Insert a part of the body.")
    number2 = input("Insert a number")
    adjective1 = input("Insert an adjective.")
    plural_noun8 = input("Insert a plural noun")
    print("It's about time!!!")
    print("Thousands of", plural_noun1, "ago, there were calendars that enabled the ancient", plural_noun2, "to divide a year into twelve", plural_noun3, ", each month into", number1, "weeks, and each week into seven", plural_noun4, ".")
    print("At first, people told time by a sun clock, sometimes known as the", noun1, "dial.")
    print("Ultimately, they invented the great timekeeping devices of today, such as the grandfather", noun2, ", the pocket", noun3, ", the alarm", noun4, ", and, of course, the", part_of_body1, "watch.")
    print("Children learn about clocks and time almost before they learn their AB", letter_of_the_alphabet1, "'s. They are taught that a day consists of 24", plural_noun5, ", and hour has 60", plural_noun6, ", and a minute has 60", plural_noun7, ".")
    print("By the time they are in kindergarten, they know if the big", part_of_body2, "is at twelve and the little", part_of_body3, "is at three, that it is", number2, "o'clock. I wish we could continue this", adjective1, "lesson, but we've run out of", plural_noun8, ".")
    return
